name: generator
description: Generates static website, pdf & odt files from xml texts
version: 1.0.0
repository: https://github.com/srix55/dvaita

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
