class FooterGen {
  FooterGen();

  String generate() {
    return '''
  <footer>
    <p>&copy; ${DateTime.now()} — Generated by Dart. Maintained by Srikanth Venkatesh. Feel free to raise github issues for issues, suggestions & discussions.</p>
    <p>Github: <a href="https://github.com/srix55/dvaita">https://github.com/srix55/dvaita</a></p>
  </footer> 
    ''';
  }
}