class FooterGen {
  FooterGen();

  String generate() {
    return '''
  <footer>
    <hr style="margin-bottom: 12px;">
    <div>&copy; ${DateTime.now()} IST — Generated by Dart. Maintained by Srikanth Venkatesh. Feel free to raise github issues for issues, suggestions & discussions.</div>
    <div>Github: <a href="https://github.com/srix55/dvaita">https://github.com/srix55/dvaita</a></div>
  </footer> 
    ''';
  }
}