import 'lander_head_gen.dart';

class LanderHtmlGen {
  static String get() {
    return '''
<!doctype html>
<html lang="sa">
${LanderHeadGen.get(title: 'द्वैतग्रन्थाः')}
<body>
  <header><h1>द्वैतग्रन्थाः</h1></header>

  <main class="content">
    <a href="smv/smv.html">सुमध्वविजयः</a>
  </main>

  <footer>
    <p>&copy; ${DateTime.now().year} — Generated by Dart</p>
  </footer>
</body>
</html>
''';
  }
}